

#ifndef _TWAI_ID_DEF_H__
#define _TWAI_ID_DEF_H__



typedef enum{
    ID_REMOTE_PING = 0x30,
    ID_REMOTE_SYNCHRONOUS,
    ID_REMOTE_SYNCHRONOUS_START,
    ID_REMOTE_SYNCHRONOUS_STOP,
// #if(CONFIG_ORSYSTEM_MODE)
    ID_REMOTE_REQUEST_ALL_REGISTER,
    ID_REMOTE_REQUEST_ALL_ANALOG_DATA,
    ID_REMOTE_REQUEST_CH1_ANALOG_DATA,
    ID_REMOTE_REQUEST_CH2_ANALOG_DATA,
    ID_REMOTE_REQUEST_CH3_ANALOG_DATA,
    ID_REMOTE_REQUEST_CH4_ANALOG_DATA,
// #else
    ID_REMOTE_GENERATOR_START,
    ID_REMOTE_GENERATOR_STOP,
// #endif
}twaI_remote_id_t;

typedef enum{
    ID_DATA_PING_DATA = 0x30,
    ID_DATA_TICK = 0x31,
    ID_DATA_OTA = 0x32,
    ID_DATA_OTA_REQUEST = 0x33,
    /// 采集相关ID
// #if(CONFIG_ORSYSTEM_MODE)
    ID_DATA_CH1_ANALOG_DATA = 0x36,
    ID_DATA_CH2_ANALOG_DATA = 0x37,
    ID_DATA_CH3_ANALOG_DATA = 0x38,
    ID_DATA_CH4_ANALOG_DATA = 0x39,
    ID_DATA_REQUEST_ANALOG_DATA = 0x3A,
    ID_DATA_REQUEST_REGISTER_DATA = 0x3B,
    ID_DATA_CONFIGURE_REGISTER_DATA = 0x3C,
    ID_DATA_COMMAND = 0x3D,
    ID_DATA_RETURN_REGISTER_DATA = 0x3E,
// #else
    
// #endif
}twai_data_id_t;












#endif
